### ISSUE TITLE
Clone URL in PR #2

### ISSUE THREAD

**Issue by hectorsector** [SRC-technology/lab.bootstrap-reason-react-app#3]
The clone URL dropped [in a comment](https://github.com/hectorsector/my-reason-react-app/pull/2#issue-276174878) assumed my repo was called `reason-todo-app` but the repo was actually called `my-reason-react-app`.

It might be best to get the clone URL from the payload. In a [`pull_request` event](https://developer.github.com/v3/activity/events/types/#webhook-payload-example-28), the payload includes both a `repo.ssh_url` and `repo.clone_url`.

**Comment by leostera** [comment]
Can we use `%actions.{action_id}.{keys}%` forms in templates?

**Comment by leostera** [comment]
Managed to fix this using the global `user.username` and `repo`. Couldn't make it work through the actions.

**Comment by hectorsector** [comment]
> Can we use `%actions.{action_id}.{keys}%` forms in templates?

You can, or you can use `%payload.repo.ssh_url%` and `%payload.repo.clone_url%`.
