### ISSUE TITLE
Link to last issue broken

### ISSUE THREAD

**Issue by hectorsector** [SRC-technology/lab.bootstrap-reason-react-app#4]
The [link to the final issue](https://github.com/hectorsector/my-reason-react-app/pull/2#issuecomment-489612995) in my PR was broken. It may be easiest to get the final issue's URL after the `createIssue` action that creates it, and then pass that URL to the `respond` action. This is also safer if the learner has opened extra issues (and so the final issue won't be the number we expect).

**Comment by leostera** [comment]
Should be fixed in https://github.com/SRC-technology/lab.bootstrap-reason-react-app/commit/37c5abf1595face5e38a3e0bb5fd65f82cf47b49
